### ISSUE TITLE
CAN1 is not working when plug in

### ISSUE THREAD

**Issue by duyvan1995** [Heavy-Vehicle-Networking-At-U-Tulsa/CAN-Logger-2#13]
CAN1 only works if the Logger stops the current file after plugging in and starts a new log file

**Comment by jeremydaily** [comment]
Is this an autobaud issue? Can you duplicate this issue and provide more description of the setup @duyvan1995?

**Comment by duyvan1995** [comment]
The issue is resolved with the latest code

**Comment by duyvan1995** [comment]
Just saw the same issue: if the logger is rebooted (was off then plugged in the BUS to start recording), the streaming and recording will only see channel 0 until I typed "stop" in the serial command and the channel 1 started showing up. Double click the button won't fix the issue

**Comment by duyvan1995** [comment]
The issue occurs when plugging in the the ECM and SSS2 only. I plugged in a TruckCape and the issue was gone. Not sure what happened

**Comment by jeremy-daily** [comment]
Can we close this again?
