### ISSUE TITLE
indicate *what* uses eeprom addresses 0 and 1

### ISSUE THREAD

**Issue by BenGardiner** [Heavy-Vehicle-Networking-At-U-Tulsa/CAN-Logger-2#24]
https://github.com/Heavy-Vehicle-Networking-At-U-Tulsa/CAN-Logger-2/blob/0bcc902eff01ec548b5f2c27af293c063587e3c3/CAN_Logger_with_Autobaud_and_Requests/CAN_Logger_with_Autobaud_and_Requests.ino#L63

Because this is a multi-module project; the comment here should indicate that it is the FlexCAN fork submodule which uses addresses 0 and 1.

**Comment by jeremydaily** [comment]
The FlexCAN module fork has the previous baudrate detected from autobaud stored. I see @BenGardiner added a comment to a patch and submitted a P.R.
